import {useState, useRef} from "react";
import {Box, Container, TextField, IconButton, CircularProgress, Chip} from "@mui/material";
import ArrowUpwardIcon from '@mui/icons-material/ArrowUpward';
import AttachFileIcon from '@mui/icons-material/AttachFile';
import {useSnackbar} from "notistack";
import {uploadFile} from "../../../api/uploadFile";
const MessageInput = ({filePath, setFilePath}) =>  {

    const { enqueueSnackbar } = useSnackbar();

    const fileInputRef = useRef(null);
    const [fileName, setFileName] = useState('');
    const [loading, setLoading] = useState(false)

    const handleDelete = () => {
        setFileName('');
        setFilePath(null)
    };

    const handleFileChange = () => {
        fileInputRef.current.click();
    };

    const handleFileInputChange = async  (event) => {
        const selectedFile = event.target.files[0];

        if (selectedFile) {
            setFileName(selectedFile.name);
            try {
                setLoading(true);
                const uploadResult = await uploadFile(selectedFile);

                console.log(uploadResult)
                setFilePath(uploadResult.path)

                if (!uploadResult.success) {
                    enqueueSnackbar("Something went wrong.", {
                        variant: "error",
                    });
                }
            } finally {
                setLoading(false);
            }
        }
    };

    return (
        <>
            <Box width={"100%"} position={"absolute"} bgcolr={"#FFF"} bottom={0} left={0}>
                <Container maxWidth={"md"}>
                    <Box width={"100%"} textAlign={"center"}>
                        <TextField
                            color={"secondary"}
                            multiline
                            variant="outlined"
                            placeholder={"Message Navirego Chat "}
                            InputProps={{
                                endAdornment: (
                                    <Box display={"flex"} alignItems={"flex-end"}>
                                        <input
                                            type="file"
                                            ref={fileInputRef}
                                            style={{ display: 'none' }}
                                            onChange={handleFileInputChange}
                                        />
                                        {
                                            (filePath !== null && fileName.length > 0) ? (
                                                <Chip label={fileName} variant={"outlined"} onDelete={handleDelete} />
                                            ) : (
                                                <IconButton onClick={handleFileChange} disabled={loading}>
                                                    {
                                                        loading ? <CircularProgress color={'secondary'} size={23.2}/> : <AttachFileIcon color={"secondary"} />
                                                    }
                                                </IconButton>
                                            )
                                        }

                                        <IconButton>
                                            <ArrowUpwardIcon color={"secondary"} />
                                        </IconButton>
                                    </Box>
                                ),
                                style: {
                                    fontSize: "15px",
                                    borderRadius: "16px",
                                    paddingTop: "8px",
                                    paddingBottom: "7px",
                                },
                            }}
                            fullWidth
                        />
                        <Box color={"rgb(86,88,105)"} fontSize={"12px"} my={2}>
                            Chatbot responses are generated by AI and may not always be accurate.
                        </Box>
                    </Box>
                </Container>
            </Box>
        </>
    );
}

export default MessageInput;
