import {useState, useRef} from "react";
import {Box, Container, TextField, IconButton, CircularProgress, Chip} from "@mui/material";
import ArrowUpwardIcon from '@mui/icons-material/ArrowUpward';
import AttachFileIcon from '@mui/icons-material/AttachFile';
import {useSnackbar} from "notistack";
import {uploadFile} from "../../../api/uploadFile";
import {sendMessage} from "../../../api/sendMessage";
const MessageInput = ({}) =>  {

    const { enqueueSnackbar } = useSnackbar();

    const [query, setQuery] = useState("")
    const [filePath, setFilePath] = useState(null);

    const fileInputRef = useRef(null);
    const [fileName, setFileName] = useState('');
    const [loading, setLoading] = useState(false)

    const handleDelete = () => {
        setFileName('');
        setFilePath(null)
    };

    const handleFileChange = () => {
        fileInputRef.current.click();
    };

    const handleFileInputChange = async  (event) => {
        const selectedFile = event.target.files[0];

        console.log(selectedFile)

        if (selectedFile) {
            setFileName(selectedFile.name);
            try {
                setLoading(true);
                const uploadResult = await uploadFile(selectedFile);

                console.log(uploadResult)
                setFilePath(uploadResult.data.path[0])

                if (!uploadResult.success) {
                    enqueueSnackbar("Something went wrong.", {
                        variant: "error",
                    });
                }
            } finally {
                setLoading(false);
            }
        }
    };

    const handleSendMessage = async () => {

        const isFileAttached = filePath !== null;

        try {
            setLoading(true);
            const messageResult = await sendMessage(isFileAttached ? filePath : query, isFileAttached ? 121 : 120, '657baa7a3b5b3dbc641e6646');

            if (!messageResult.success) {
                enqueueSnackbar('Failed to send message.', {
                    variant: 'error',
                });
            }
        } finally {
            setLoading(false);
        }

        setQuery("");
        handleDelete();
    };

    return (
        <>
            <Box width={"100%"} position={"absolute"} bottom={0} left={0} sx={{backgroundColor: "#FFF"}}>
                <Container maxWidth={"md"}>
                    <Box width={"100%"} textAlign={"center"}>
                        <input
                            type="file"
                            ref={fileInputRef}
                            style={{ display: 'none' }}
                            onChange={handleFileInputChange}
                        />
                        <TextField
                            value={query}
                            onChange={(event) => {
                                setQuery(event.target.value);
                            }}
                            color={"secondary"}
                            multiline
                            variant="outlined"
                            placeholder={"Message Navirego Chat "}
                            InputProps={{
                                endAdornment: (
                                    <Box display={"flex"} alignItems={"flex-end"}>
                                        {
                                            (filePath !== null && fileName.length > 0) ? (
                                                <Chip label={fileName} variant={"outlined"} onDelete={handleDelete} />
                                            ) : (
                                                <IconButton onClick={handleFileChange} disabled={loading}>
                                                    {
                                                        loading ? <CircularProgress color={'secondary'} size={23.2}/> : <AttachFileIcon color={"secondary"} />
                                                    }
                                                </IconButton>
                                            )
                                        }

                                        <IconButton onClick={handleSendMessage} disabled={loading}>
                                            <ArrowUpwardIcon color={"secondary"} />
                                        </IconButton>
                                    </Box>
                                ),
                                style: {
                                    fontSize: "15px",
                                    borderRadius: "16px",
                                    paddingTop: "8px",
                                    paddingBottom: "7px",
                                },
                            }}
                            fullWidth
                        />
                        <Box color={"rgb(86,88,105)"} fontSize={"12px"} my={2}>
                            Chatbot responses are generated by AI and may not always be accurate.
                        </Box>
                    </Box>
                </Container>
            </Box>
        </>
    );
}

export default MessageInput;
